// Mock the supabase client because importing @/auth/username transitively imports
// supabaseClient.ts which throws at module load time if EXPO_PUBLIC_SUPABASE_* envs
// are not set (Jest does not auto-load .env). The pure validators under test do not
// need a real client.
jest.mock("@/auth/supabaseClient", () => ({ supabase: {} }));

import { isValidUsername, isAutoGeneratedUsername } from "@/auth/username";

describe("isValidUsername", () => {
  it.each([
    ["abc", true],
    ["abc_123", true],
    ["a_very_long_user", true],
    ["ab", false],
    ["AB", false],
    ["with-dash", false],
    ["with space", false],
    ["", false],
    ["a".repeat(21), false]
  ])("'%s' -> %s", (input, expected) => {
    expect(isValidUsername(input)).toBe(expected);
  });
});

describe("isAutoGeneratedUsername", () => {
  // Note: changed "oscar_4f2k" -> "oscar_4f2a" because the auto-generated suffix
  // must be 4 hex chars (the Postgres function uses md5(...)::text), and 'k' is not hex.
  it("matches pattern <base>_<4hex>", () => {
    expect(isAutoGeneratedUsername("oscar_4f2a")).toBe(true);
    expect(isAutoGeneratedUsername("user_a1b2")).toBe(true);
    expect(isAutoGeneratedUsername("oscar")).toBe(false);
    expect(isAutoGeneratedUsername("oscar_panini")).toBe(false);
  });
});
