// Mapeo código de país → emoji bandera. Para Inglaterra y Escocia se usan los
// flags subdivisión de UK (pueden no renderizar en algunos sistemas viejos).
const FLAGS: Record<string, string> = {
  ARG: "🇦🇷",
  BRA: "🇧🇷",
  USA: "🇺🇸",
  MEX: "🇲🇽",
  CAN: "🇨🇦",
  ESP: "🇪🇸",
  FRA: "🇫🇷",
  ENG: "🏴\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}",
  GER: "🇩🇪",
  POR: "🇵🇹",
  ITA: "🇮🇹",
  NED: "🇳🇱",
  BEL: "🇧🇪",
  CRO: "🇭🇷",
  URU: "🇺🇾",
  COL: "🇨🇴",
  ECU: "🇪🇨",
  PAR: "🇵🇾",
  CHI: "🇨🇱",
  PER: "🇵🇪",
  JPN: "🇯🇵",
  KOR: "🇰🇷",
  AUS: "🇦🇺",
  IRN: "🇮🇷",
  KSA: "🇸🇦",
  QAT: "🇶🇦",
  IRQ: "🇮🇶",
  JOR: "🇯🇴",
  UZB: "🇺🇿",
  MAR: "🇲🇦",
  SEN: "🇸🇳",
  EGY: "🇪🇬",
  TUN: "🇹🇳",
  ALG: "🇩🇿",
  GHA: "🇬🇭",
  CIV: "🇨🇮",
  CMR: "🇨🇲",
  RSA: "🇿🇦",
  CPV: "🇨🇻",
  COD: "🇨🇩",
  BFA: "🇧🇫",
  NGA: "🇳🇬",
  CRC: "🇨🇷",
  PAN: "🇵🇦",
  JAM: "🇯🇲",
  HAI: "🇭🇹",
  CUW: "🇨🇼",
  NZL: "🇳🇿",
  SUI: "🇨🇭",
  AUT: "🇦🇹",
  POL: "🇵🇱",
  CZE: "🇨🇿",
  TUR: "🇹🇷",
  SCO: "🏴\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
  NOR: "🇳🇴",
  SWE: "🇸🇪",
  DEN: "🇩🇰",
  HUN: "🇭🇺",
  UKR: "🇺🇦",
  BIH: "🇧🇦"
};

export function getTeamFlag(code: string | null | undefined): string {
  if (!code) return "🏳️";
  return FLAGS[code] ?? "🏳️";
}
