import { supabase } from "./supabaseClient";

const VALID_RE = /^[a-z0-9_]{3,20}$/;
const AUTO_RE = /^[a-z][a-z0-9]{0,11}_[a-f0-9]{4}$/;

export function isValidUsername(s: string): boolean {
  return VALID_RE.test(s);
}

export function isAutoGeneratedUsername(s: string): boolean {
  return AUTO_RE.test(s);
}

export async function isUsernameTaken(username: string, excludeUserId?: string): Promise<boolean> {
  let q = supabase.from("profiles").select("id", { count: "exact", head: true }).eq("username", username);
  if (excludeUserId) q = q.neq("id", excludeUserId);
  const { count, error } = await q;
  if (error) throw error;
  return (count ?? 0) > 0;
}
