// Generado a partir de assets/flags-png/<CODE>.png (+ @2x + @3x).
// Para regenerar los PNG desde los SVG: node scripts/svg-to-png-flags.js
// React Native elige automaticamente la variante segun la densidad del device.

import type { ImageSourcePropType } from "react-native";

export const FLAG_PNG: Record<string, ImageSourcePropType> = {
  ALG: require("../../../assets/flags-png/ALG.png"),
  ARG: require("../../../assets/flags-png/ARG.png"),
  AUS: require("../../../assets/flags-png/AUS.png"),
  AUT: require("../../../assets/flags-png/AUT.png"),
  BEL: require("../../../assets/flags-png/BEL.png"),
  BIH: require("../../../assets/flags-png/BIH.png"),
  BRA: require("../../../assets/flags-png/BRA.png"),
  CAN: require("../../../assets/flags-png/CAN.png"),
  CIV: require("../../../assets/flags-png/CIV.png"),
  COD: require("../../../assets/flags-png/COD.png"),
  COL: require("../../../assets/flags-png/COL.png"),
  CPV: require("../../../assets/flags-png/CPV.png"),
  CRO: require("../../../assets/flags-png/CRO.png"),
  CUW: require("../../../assets/flags-png/CUW.png"),
  CZE: require("../../../assets/flags-png/CZE.png"),
  ECU: require("../../../assets/flags-png/ECU.png"),
  EGY: require("../../../assets/flags-png/EGY.png"),
  ENG: require("../../../assets/flags-png/ENG.png"),
  ESP: require("../../../assets/flags-png/ESP.png"),
  FRA: require("../../../assets/flags-png/FRA.png"),
  GER: require("../../../assets/flags-png/GER.png"),
  GHA: require("../../../assets/flags-png/GHA.png"),
  HAI: require("../../../assets/flags-png/HAI.png"),
  IRN: require("../../../assets/flags-png/IRN.png"),
  IRQ: require("../../../assets/flags-png/IRQ.png"),
  JOR: require("../../../assets/flags-png/JOR.png"),
  JPN: require("../../../assets/flags-png/JPN.png"),
  KOR: require("../../../assets/flags-png/KOR.png"),
  KSA: require("../../../assets/flags-png/KSA.png"),
  MAR: require("../../../assets/flags-png/MAR.png"),
  MEX: require("../../../assets/flags-png/MEX.png"),
  NED: require("../../../assets/flags-png/NED.png"),
  NOR: require("../../../assets/flags-png/NOR.png"),
  NZL: require("../../../assets/flags-png/NZL.png"),
  PAN: require("../../../assets/flags-png/PAN.png"),
  PAR: require("../../../assets/flags-png/PAR.png"),
  POR: require("../../../assets/flags-png/POR.png"),
  QAT: require("../../../assets/flags-png/QAT.png"),
  RSA: require("../../../assets/flags-png/RSA.png"),
  SCO: require("../../../assets/flags-png/SCO.png"),
  SEN: require("../../../assets/flags-png/SEN.png"),
  SUI: require("../../../assets/flags-png/SUI.png"),
  SWE: require("../../../assets/flags-png/SWE.png"),
  TUN: require("../../../assets/flags-png/TUN.png"),
  TUR: require("../../../assets/flags-png/TUR.png"),
  URU: require("../../../assets/flags-png/URU.png"),
  USA: require("../../../assets/flags-png/USA.png"),
  UZB: require("../../../assets/flags-png/UZB.png")
};
